pipeline {
  options(parameters([booleanParam(defaultValue: true, description: '', name: 'build'), booleanParam(defaultValue: true, description: '', name: 'deploy')])])
  agent any
  
  stages{
    stage ('Print Hello') {
      steps {
        echo 'Hello' 
      }  
    }

    stage('Print World') {
      steps {
        echo 'World!'
      } 
    }
  }
   
}
