pipeline {
  parameters{
      booleanParam(defaultValue: true, description: '', name: 'build')
      booleanParam(defaultValue: true, description: '', name: 'archive')
  }
  agent any
  
  stages{
    stage ('Build') {
    when { expression { return params.build } }
      steps {
        echo 'Building...' 
      }  
    }

    stage('Archive') {
      when { expression { return params.deploy } }
      steps {
        echo 'Archiving...'
      } 
    }

    stage('Simple Deploy Prompt') {
      steps {
        input ([ 
                message: 'Are you sure you want to deploy into production?',
                ok: 'Yes'
        ]) 

        echo 'Deploying...'
      } 
    }

    stage('Deploy Prompt With a Boolean Choice') {
      steps {
        input ([ 
                message: '<Message>',
                parameters: [booleanParam(defaultValue: true,
                description: '<Boolean Value>', name: 'snapshot')] 
        ]) 

        echo 'Deploying snapshot...'
      } 
    }

    stage('Deploy Prompt With a list of choices') {
      steps {
        input ([ 
                message: '<Message>',
                parameters: [choice(choices: ['A', 'B', 'C']
                description: 'Make a choice', name: 'Options')] 
        ]) 

        echo 'Deploying snapshot...'
      } 
    }

  }
}
