pipeline {
  parameters{
      booleanParam(defaultValue: true, description: '', name: 'build')
      booleanParam(defaultValue: true, description: '', name: 'archive')
  }
  agent any
  
  stages{
    stage ('Build') {
    when { expression { return params.build } }
      steps {
        echo 'Building...' 
      }  
    }

    stage('Archive') {
      when { expression { return params.deploy } }
      steps {
        echo 'Archiving...'
      } 
    }

    stage('Simple Deploy Prompt') {
      steps {
        input ([ 
                message: 'Are you sure you want to deploy into production?',
                ok: 'Yes'
        ]) 

        echo 'Deploying...'
      } 
    }

    stage('Deploy Prompt With a Boolean Choice') {
      steps {
        input ([ 
                message: '<Message>',
                parameters: [booleanParam(defaultValue: true,
                description: '<Boolean Value>', name: 'snapshot')] 
        ]) 

        echo 'Deploying snapshot...'
      } 
    }

    stage('Deploy Prompt With a list of options') {
      steps {
        input ([ 
                message: '<Message>',
                parameters: [choice(choices: ['A', 'B', 'C'],
                description: 'Make a choice', name: 'Options')] 
        ]) 

        echo 'Deploying snapshot...'
      } 
    }

    stage('Deploy Prompt With an input box taking multi-line strings') {
      steps {
        input ([ 
                message: '<Message>',
                parameters: [text(defaultValue: ''' Type Something Here ''',
                description: '', name: 'User Input')] 
        ]) 

        echo 'Deploying snapshot...'
      } 
    }

    stage('Deploy Prompt With hidden password field') {
      steps {
        input ([ 
                message: '<Message>',
                parameters: [password(defaultValue: '',
                description: 'Enter Password', name: 'User Password')] 
        ]) 

        echo 'Deploying snapshot...'
      } 
    }

    stage('Deploy Prompt combining parameters') {
      steps {
        def user = input ([ 
                message: 'Login',
                parameters: [string(defaultValue: '', description:
                'Username', name: 'username'),
                password(defaultValue: '',
                description: 'Enter Password', name: 'password')] 
        ]) 
        echo "Username= " + user['username']
        echo "Password= ${user['password']}" 
        echo user.username + " " + user.password

        echo 'Deploying snapshot...'
      } 
    }

  }
}
